/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Yonathan Carvajal
 */
public class Busqueda extends javax.swing.JDialog {

    
    
    public void transparecia() {
        abrirarchivos.setOpaque(false);
        abrirarchivos.setContentAreaFilled(false);
        
        editar.setOpaque(false);
        editar.setContentAreaFilled(false);

//        crearcliente.setOpaque(false);
        panelprincipal.setOpaque(false);
//        crearcliente.setContentAreaFilled(false);

    }
    /**
     * Creates new form Busqueda
     */
    public Busqueda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        transparecia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelprincipal = new javax.swing.JPanel();
        txtbuscar = new rojerusan.RSMetroTextFullPlaceHolder();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos = new rojerusan.RSTableMetro();
        editar = new javax.swing.JButton();
        abrirarchivos = new javax.swing.JButton();
        filtro = new rojerusan.RSComboMetro();
        filtrocliente = new rojerusan.RSComboMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setBackground(new java.awt.Color(255, 153, 153));
        panelprincipal.setMaximumSize(new java.awt.Dimension(1280, 1080));
        panelprincipal.setName("panelpricipal"); // NOI18N
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtbuscar.setBorderColor(new java.awt.Color(102, 102, 102));
        txtbuscar.setPhColor(new java.awt.Color(210, 43, 7));
        panelprincipal.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabladatos.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tabladatos.setColorFilasForeground1(new java.awt.Color(216, 74, 44));
        tabladatos.setColorFilasForeground2(new java.awt.Color(216, 74, 44));
        tabladatos.setColorSelBackgound(new java.awt.Color(216, 74, 44));
        tabladatos.setRowHeight(30);
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabladatos);

        panelprincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1000, 460));

        editar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editar.setText("Editar");
        editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        panelprincipal.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 140, 70));

        abrirarchivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        abrirarchivos.setForeground(new java.awt.Color(255, 255, 255));
        abrirarchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        abrirarchivos.setText("Archivos");
        abrirarchivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        abrirarchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirarchivosActionPerformed(evt);
            }
        });
        panelprincipal.add(abrirarchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 170, 70));

        filtro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nit\t", "nombre", "codigo" }));
        filtro.setColorArrow(new java.awt.Color(0, 0, 0));
        filtro.setColorBorde(new java.awt.Color(102, 102, 102));
        filtro.setColorFondo(new java.awt.Color(102, 102, 102));
        filtro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelprincipal.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 140, 40));

        filtrocliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "todo", "cliente_potencial", "cliente" }));
        filtrocliente.setColorArrow(new java.awt.Color(0, 0, 0));
        filtrocliente.setColorBorde(new java.awt.Color(102, 102, 102));
        filtrocliente.setColorFondo(new java.awt.Color(102, 102, 102));
        filtrocliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelprincipal.add(filtrocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 190, 40));

        jPanel1.add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 620));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        //                int selecionar = tabladatos.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tabladatosMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

    }//GEN-LAST:event_editarActionPerformed

    private void abrirarchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirarchivosActionPerformed

    }//GEN-LAST:event_abrirarchivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Busqueda dialog = new Busqueda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton abrirarchivos;
    public javax.swing.JButton editar;
    public rojerusan.RSComboMetro filtro;
    public rojerusan.RSComboMetro filtrocliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelprincipal;
    public rojerusan.RSTableMetro tabladatos;
    public rojerusan.RSMetroTextFullPlaceHolder txtbuscar;
    // End of variables declaration//GEN-END:variables
}
