/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Yonathan Carvajal
 */
public class Carpetas extends javax.swing.JDialog {

    
    
    public void transparecia() {
    

        agregarcarpeta.setOpaque(false);
        agregarcarpeta.setContentAreaFilled(false);
//        agregarcarpeta.setBorderPainted(false);

        eliminaragregarcarpeta.setOpaque(false);
        eliminaragregarcarpeta.setContentAreaFilled(false);
//        eliminaragregarcarpeta.setBorderPainted(false);

        guardarcarpeta.setOpaque(false);
        guardarcarpeta.setContentAreaFilled(false);
        
        agregarsubcarpeta.setOpaque(false);
        agregarsubcarpeta.setContentAreaFilled(false);
//        guardarcarpeta.setBorderPainted(false);

       
        panel2panel3.setOpaque(false);
        arbol.setOpaque(false);
       

    }
    /**
     * Creates new form Carpetas
     */
    public Carpetas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setResizable(false);
//        ImageIcon rm = new ImageIcon(getClass().getResource("/img/rm1.jpg"));
//        Icon fondo = new ImageIcon(rm.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT));
//        jLabel1.setIcon(fondo);
        transparecia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenu = new javax.swing.JPopupMenu();
        agregarmenuitem = new javax.swing.JMenuItem();
        eliminarmenuitem = new javax.swing.JMenuItem();
        panel2panel3 = new javax.swing.JPanel();
        guardarcarpeta = new javax.swing.JButton();
        agregarcarpeta = new javax.swing.JButton();
        eliminaragregarcarpeta = new javax.swing.JButton();
        agregarsubcarpeta = new javax.swing.JButton();
        tr = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        txtdirectorio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        agregarmenuitem.setText("Nueva carpeta");
        PopupMenu.add(agregarmenuitem);

        eliminarmenuitem.setText("Eliminar");
        PopupMenu.add(eliminarmenuitem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel2panel3.setBackground(new java.awt.Color(204, 204, 255));
        panel2panel3.setName("panel2panel3"); // NOI18N
        panel2panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarcarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        guardarcarpeta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 74, 44), 2, true));
        panel2panel3.add(guardarcarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 72, -1));

        agregarcarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        agregarcarpeta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 74, 44), 2, true));
        panel2panel3.add(agregarcarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 65, 57));

        eliminaragregarcarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminaragregarcarpeta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 74, 44), 2, true));
        panel2panel3.add(eliminaragregarcarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 65, -1));

        agregarsubcarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subcarpetas.png"))); // NOI18N
        agregarsubcarpeta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 74, 44), 2, true));
        panel2panel3.add(agregarsubcarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 65, 57));

        arbol.setComponentPopupMenu(PopupMenu);
        tr.setViewportView(arbol);

        panel2panel3.add(tr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 550));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtdirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtdirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        panel2panel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 310, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carpetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carpetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carpetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carpetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Carpetas dialog = new Carpetas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopupMenu;
    public javax.swing.JButton agregarcarpeta;
    public javax.swing.JMenuItem agregarmenuitem;
    public javax.swing.JButton agregarsubcarpeta;
    public javax.swing.JTree arbol;
    public javax.swing.JButton eliminaragregarcarpeta;
    public javax.swing.JMenuItem eliminarmenuitem;
    public javax.swing.JButton guardarcarpeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel2panel3;
    public javax.swing.JScrollPane tr;
    private javax.swing.JTextField txtdirectorio;
    // End of variables declaration//GEN-END:variables
}
