/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;


import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Yonathan Carvajal
 */
public class Otros extends javax.swing.JDialog {

    public void transparecia() {
        panelotros.setOpaque(false);

        eliminaragregarclase.setOpaque(false);
        eliminaragregarclase.setContentAreaFilled(false);

        eliminarllego.setOpaque(false);
        eliminarllego.setContentAreaFilled(false);

        agregarclase.setOpaque(false);
        agregarclase.setContentAreaFilled(false);

        eliminarclase.setOpaque(false);
        eliminarclase.setContentAreaFilled(false);

        guardarclase.setOpaque(false);
        guardarclase.setContentAreaFilled(false);

        agregarllego.setOpaque(false);
        agregarllego.setContentAreaFilled(false);

        eliminaragregarllego.setOpaque(false);
        eliminaragregarllego.setContentAreaFilled(false);

        guardarllego.setOpaque(false);
        guardarllego.setContentAreaFilled(false);

    }

    /**
     * Creates new form Otros
     */
    public Otros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
//        ImageIcon rm = new ImageIcon(getClass().getResource("/img/rm1.jpg"));
//        Icon fondo = new ImageIcon(rm.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT));
//        jLabel1.setIcon(fondo);
        transparecia();
        this.getRootPane().registerKeyboardAction(e -> {
            this.dispose();
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelotros = new javax.swing.JPanel();
        agregarclase = new javax.swing.JButton();
        eliminaragregarclase = new javax.swing.JButton();
        guardarclase = new javax.swing.JButton();
        agregarllego = new javax.swing.JButton();
        eliminaragregarllego = new javax.swing.JButton();
        guardarllego = new javax.swing.JButton();
        eliminarclase = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaagregarclase = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaclase = new javax.swing.JTable();
        txtregistrarclase = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablallego = new javax.swing.JTable();
        txtregistrarllego = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaagregarllego = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        eliminarllego = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelotros.setBackground(new java.awt.Color(0, 102, 102));
        panelotros.setName("panelotros"); // NOI18N
        panelotros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        agregarclase.setText("Agregar");
        agregarclase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        panelotros.add(agregarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 110, 57));

        eliminaragregarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminaragregarclase.setText("Eliminar");
        eliminaragregarclase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        panelotros.add(eliminaragregarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 110, -1));

        guardarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        guardarclase.setText("Guardar");
        guardarclase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        panelotros.add(guardarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 110, -1));

        agregarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        agregarllego.setText("Agregar");
        agregarllego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        panelotros.add(agregarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 110, 57));

        eliminaragregarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminaragregarllego.setText("Eliminar");
        eliminaragregarllego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        panelotros.add(eliminaragregarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 110, -1));

        guardarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        guardarllego.setText("Guardar");
        guardarllego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));
        panelotros.add(guardarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 110, -1));

        eliminarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminarclase.setText("Eliminar");
        eliminarclase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        panelotros.add(eliminarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, -1));

        tablaagregarclase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(tablaagregarclase);

        panelotros.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 170, 180));

        tablaclase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaclase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(tablaclase);

        panelotros.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 170, 210));
        panelotros.add(txtregistrarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 170, -1));

        tablallego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(tablallego);

        panelotros.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 210));
        panelotros.add(txtregistrarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 170, -1));

        tablaagregarllego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(tablaagregarllego);

        panelotros.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 170, 180));

        jPanel1.setBackground(new java.awt.Color(159, 213, 209));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        panelotros.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 660, 230));

        jPanel2.setBackground(new java.awt.Color(159, 213, 209));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        eliminarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        eliminarllego.setText("Eliminar");
        eliminarllego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 43, 7), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarllego, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(548, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarllego)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        panelotros.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 660, 230));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        panelotros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 708, 522));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelotros, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Otros dialog = new Otros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarclase;
    public javax.swing.JButton agregarllego;
    public javax.swing.JButton eliminaragregarclase;
    public javax.swing.JButton eliminaragregarllego;
    public javax.swing.JButton eliminarclase;
    public javax.swing.JButton eliminarllego;
    public javax.swing.JButton guardarclase;
    public javax.swing.JButton guardarllego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelotros;
    public javax.swing.JTable tablaagregarclase;
    public javax.swing.JTable tablaagregarllego;
    public javax.swing.JTable tablaclase;
    public javax.swing.JTable tablallego;
    public javax.swing.JTextField txtregistrarclase;
    public javax.swing.JTextField txtregistrarllego;
    // End of variables declaration//GEN-END:variables
}
