/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Yonathan Carvajal
 */
public class Otros extends javax.swing.JDialog {

    
     public void transparecia() {
        panelotros.setOpaque(false);
    }
    
    /**
     * Creates new form Otros
     */
    public Otros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
//        ImageIcon rm = new ImageIcon(getClass().getResource("/img/rm1.jpg"));
//        Icon fondo = new ImageIcon(rm.getImage().getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_DEFAULT));
//        jLabel1.setIcon(fondo);
        transparecia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelotros = new javax.swing.JPanel();
        eliminarllego = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tablallego = new rojerusan.RSTableMetro();
        txtregistrarllego = new rojerusan.RSMetroTextFullPlaceHolder();
        jScrollPane11 = new javax.swing.JScrollPane();
        tablaagregarllego = new rojerusan.RSTableMetro();
        agregarclase = new javax.swing.JButton();
        eliminaragregarclase = new javax.swing.JButton();
        guardarclase = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tablaclase = new rojerusan.RSTableMetro();
        jScrollPane13 = new javax.swing.JScrollPane();
        tablaagregarclase = new rojerusan.RSTableMetro();
        txtregistrarclase = new rojerusan.RSMetroTextFullPlaceHolder();
        agregarllego = new javax.swing.JButton();
        eliminaragregarllego = new javax.swing.JButton();
        guardarllego = new javax.swing.JButton();
        eliminarclase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelotros.setBackground(new java.awt.Color(0, 102, 102));
        panelotros.setName("panelotros"); // NOI18N
        panelotros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        panelotros.add(eliminarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        tablallego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tablallego.setRowHeight(30);
        jScrollPane10.setViewportView(tablallego);

        panelotros.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 276, 260));

        txtregistrarllego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrarllegoActionPerformed(evt);
            }
        });
        panelotros.add(txtregistrarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 276, -1));

        tablaagregarllego.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tablaagregarllego.setRowHeight(30);
        jScrollPane11.setViewportView(tablaagregarllego);

        panelotros.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 276, 210));

        agregarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        panelotros.add(agregarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, 57));

        eliminaragregarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        panelotros.add(eliminaragregarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 65, -1));

        guardarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        panelotros.add(guardarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 72, -1));

        tablaclase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tablaclase.setRowHeight(30);
        jScrollPane12.setViewportView(tablaclase);

        panelotros.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 276, 260));

        tablaagregarclase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tablaagregarclase.setRowHeight(30);
        jScrollPane13.setViewportView(tablaagregarclase);

        panelotros.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 276, 210));

        txtregistrarclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregistrarclaseActionPerformed(evt);
            }
        });
        panelotros.add(txtregistrarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 276, -1));

        agregarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        panelotros.add(agregarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, 57));

        eliminaragregarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        panelotros.add(eliminaragregarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 65, -1));

        guardarllego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        panelotros.add(guardarllego, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 72, -1));

        eliminarclase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        panelotros.add(eliminarclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtregistrarllegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrarllegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrarllegoActionPerformed

    private void txtregistrarclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregistrarclaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregistrarclaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Otros dialog = new Otros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarclase;
    public javax.swing.JButton agregarllego;
    public javax.swing.JButton eliminaragregarclase;
    public javax.swing.JButton eliminaragregarllego;
    public javax.swing.JButton eliminarclase;
    public javax.swing.JButton eliminarllego;
    public javax.swing.JButton guardarclase;
    public javax.swing.JButton guardarllego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JPanel panelotros;
    public rojerusan.RSTableMetro tablaagregarclase;
    public rojerusan.RSTableMetro tablaagregarllego;
    public rojerusan.RSTableMetro tablaclase;
    public rojerusan.RSTableMetro tablallego;
    public rojerusan.RSMetroTextFullPlaceHolder txtregistrarclase;
    public rojerusan.RSMetroTextFullPlaceHolder txtregistrarllego;
    // End of variables declaration//GEN-END:variables
}
