/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Consultas.Consultas_Cliente;
import Consultas.Consultas_usuario;
import Controladores.TablaClientesController;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import Modelos.Cliente;
import Modelos.Usuario;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Yonathan Carvajal
 */
public class Principal extends javax.swing.JFrame {

    Usuario modu;
    Consultas_usuario cons;

    public void transparecia() {
        configuraciones1.setOpaque(false);
        configuraciones1.setContentAreaFilled(false);
//        configuraciones1.setBorderPainted(false);

        crearcliente.setOpaque(false);
        crearcliente.setContentAreaFilled(false);
//        crearcliente.setBorderPainted(false);

        otro.setOpaque(false);
        otro.setContentAreaFilled(false);

        crearusuario.setOpaque(false);
        crearusuario.setContentAreaFilled(false);

        carpetas.setOpaque(false);
        carpetas.setContentAreaFilled(false);

        backup.setOpaque(false);
        backup.setContentAreaFilled(false);

        btnterminar.setOpaque(false);
        btnterminar.setContentAreaFilled(false);

        Cotizaciones.setOpaque(false);
        Cotizaciones.setContentAreaFilled(false);
        
        acciones.setOpaque(false);
        acciones.setContentAreaFilled(false);

        jPanel2.setOpaque(false);
        jPanel4.setOpaque(false);
    }
//   DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    public Principal(Usuario modu) throws IOException, ParseException {
        initComponents();
        transparecia();
        BufferedImage image = null;
        Image icon = new ImageIcon(getClass().getResource("/img/Organize.png")).getImage();
        setIconImage(icon);        
        this.getRootPane().registerKeyboardAction(e -> {
            this.dispose();
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_IN_FOCUSED_WINDOW);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        int ancho = (int) tamanio.getWidth();
        int alto = (int) tamanio.getHeight();
        this.setSize(new Dimension(ancho, alto));
        jPanel2.setPreferredSize(new Dimension(ancho, 70));
        jPanel4.setPreferredSize(new Dimension(ancho-20, alto-170));
//        tabladatos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        ImageIcon rm = new ImageIcon(getClass().getResource("/img/fondo2.png"));
        Icon fondo = new ImageIcon(rm.getImage().getScaledInstance(this.getWidth(), alto, Image.SCALE_DEFAULT));

        jLabel1.setIcon(fondo);

        this.modu = modu;
//        System.out.println(modu.getConfiguraciones());

        if (modu.getRol()
                == 1) {
        } else {
            if (modu.getRol() == 2) {
                if (modu.getConfiguraciones() == 0) {
                    configuraciones1.setVisible(false);
                }
                if (modu.getCrearcliente() == 0) {
                    crearcliente.setVisible(false);
                }
                if (modu.getCarpetas() == 0) {
                    carpetas.setVisible(false);
                }
                if (modu.getOtros() == 0) {
                    otro.setVisible(false);
                }
                if (modu.getCrearusuarios() == 0) {
                    crearusuario.setVisible(false);
                }
                if (modu.getBackups() == 0) {
                    backup.setVisible(false);
                }
                
            }
        }
        Cliente modelo = new Cliente();
        Consultas_Cliente consulta = new Consultas_Cliente();
        TablaClientesController bc = new TablaClientesController(modelo, consulta, this);
        bc.iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        popup = new javax.swing.JPopupMenu();
        abrirdirectorio = new javax.swing.JMenuItem();
        editarcliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        backup = new javax.swing.JMenuItem();
        btnagregaractividad = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnterminar = new javax.swing.JButton();
        otro = new javax.swing.JButton();
        configuraciones1 = new javax.swing.JButton();
        Cotizaciones = new javax.swing.JButton();
        carpetas = new javax.swing.JButton();
        crearusuario = new javax.swing.JButton();
        acciones = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        filtro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        crearcliente = new javax.swing.JButton();
        txtbuscar2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        abrirdirectorio.setText("Abrir directorio");
        popup.add(abrirdirectorio);

        editarcliente.setText("Editar Cliente");
        popup.add(editarcliente);
        popup.add(jSeparator1);

        backup.setText("Backup");
        popup.add(backup);

        btnagregaractividad.setText("Agregar Actividad");
        popup.add(btnagregaractividad);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(209, 235, 247));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Organizador");

        btnterminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnterminar.setForeground(new java.awt.Color(255, 255, 255));
        btnterminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir48px.png"))); // NOI18N
        btnterminar.setText("Terminar");
        btnterminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        btnterminar.setFocusPainted(false);
        btnterminar.setOpaque(false);
        btnterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnterminarActionPerformed(evt);
            }
        });

        otro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        otro.setForeground(new java.awt.Color(255, 255, 255));
        otro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/more.png"))); // NOI18N
        otro.setText("Otros");
        otro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        otro.setFocusable(false);
        otro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        otro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        configuraciones1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        configuraciones1.setForeground(new java.awt.Color(255, 255, 255));
        configuraciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/track.png"))); // NOI18N
        configuraciones1.setText("Directorio");
        configuraciones1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        configuraciones1.setFocusPainted(false);
        configuraciones1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        configuraciones1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        configuraciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuraciones1ActionPerformed(evt);
            }
        });

        Cotizaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cotizaciones.setForeground(new java.awt.Color(255, 255, 255));
        Cotizaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/cotizacion.png"))); // NOI18N
        Cotizaciones.setText("Cotizaciones");
        Cotizaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        Cotizaciones.setFocusPainted(false);
        Cotizaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Cotizaciones.setOpaque(false);
        Cotizaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        carpetas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carpetas.setForeground(new java.awt.Color(255, 255, 255));
        carpetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principal/folder.png"))); // NOI18N
        carpetas.setText("Carpetas");
        carpetas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        carpetas.setFocusPainted(false);
        carpetas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        carpetas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        crearusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crearusuario.setForeground(new java.awt.Color(255, 255, 255));
        crearusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sync32.png"))); // NOI18N
        crearusuario.setText("Usuarios");
        crearusuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        crearusuario.setFocusPainted(false);
        crearusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        crearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearusuarioActionPerformed(evt);
            }
        });

        acciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        acciones.setForeground(new java.awt.Color(255, 255, 255));
        acciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearuser32.png"))); // NOI18N
        acciones.setText("Acciones");
        acciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        acciones.setFocusPainted(false);
        acciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        acciones.setOpaque(false);
        acciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(otro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(configuraciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cotizaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(carpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnterminar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carpetas)
                    .addComponent(Cotizaciones)
                    .addComponent(configuraciones1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(otro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(crearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnterminar)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "electronica", "sucursal", "cliente potencial" }));

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16", "Title 17", "Title 18", "Title 19", "Title 20", "Title 21", "Title 22", "Title 23", "Title 24", "Title 25", "Title 26", "Title 27", "Title 28", "Title 29", "Title 30"
            }
        ));
        tabladatos.setToolTipText("!Cliclk derecho para mas opciones¡");
        tabladatos.setComponentPopupMenu(popup);
        jScrollPane1.setViewportView(tabladatos);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter para buscar");

        crearcliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crearcliente.setForeground(new java.awt.Color(255, 255, 255));
        crearcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearuser32.png"))); // NOI18N
        crearcliente.setText("Crearcliente");
        crearcliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(210, 43, 7), 2, true));
        crearcliente.setFocusPainted(false);
        crearcliente.setHideActionText(true);
        crearcliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crearcliente.setOpaque(false);
        crearcliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                        .addComponent(crearcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3))
                    .addComponent(crearcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void configuraciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuraciones1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configuraciones1ActionPerformed

    private void crearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearusuarioActionPerformed

    private void btnterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnterminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnterminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Cotizaciones;
    public javax.swing.JMenuItem abrirdirectorio;
    public javax.swing.JButton acciones;
    public javax.swing.JMenuItem backup;
    public javax.swing.JMenuItem btnagregaractividad;
    public javax.swing.JButton btnterminar;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton carpetas;
    public javax.swing.JButton configuraciones1;
    public javax.swing.JButton crearcliente;
    public javax.swing.JButton crearusuario;
    public javax.swing.JMenuItem editarcliente;
    public javax.swing.JComboBox<String> filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JButton otro;
    public javax.swing.JPopupMenu popup;
    public javax.swing.JTable tabladatos;
    public javax.swing.JTextField txtbuscar;
    public javax.swing.JTextField txtbuscar2;
    // End of variables declaration//GEN-END:variables

}
