/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Consultas.Consultas_Clase;
import Consultas.Consultas_Cliente_Potencial;
import Consultas.Consultas_Configuraciones;
import Consultas.Consultas_Directorio;
import Consultas.Consultas_Documentos;
import Consultas.Consultas_Llego;
import Consultas.Consultas_Servicio;
import Consultas.Consultas_Servicios_has_Clientes_Potenciales;
import Consultas.Consultas_usuario;
import buscador.Dialogos;
import controlador.ClaseController;
import controlador.Cliente_PotencialController;
import controlador.ConfiguracionesController;
import controlador.DirectorioController;
import controlador.EditarController;
import controlador.LlegoController;
import controlador.ServicioController;
import controlador.UsuarioController;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Clases;
import modelo.Cliente_Potencial;
import modelo.Configuracion;
import modelo.Directorio;
import modelo.Documentos;
import modelo.Llego;
import modelo.Servicio;
import modelo.Servicios_has_Clientes_Potenciales;

/**
 *
 * @author Yonathan Carvajal
 */
public class Principal extends javax.swing.JFrame {

    public void transparecia() {

        abrirarchivos.setOpaque(false);
        abrirarchivos.setContentAreaFilled(false);
        abrirarchivos.setBorderPainted(false);
        
        configuraciones1.setOpaque(false);
        configuraciones1.setContentAreaFilled(false);
        configuraciones1.setBorderPainted(false);
        
        crearcliente.setOpaque(false);
        crearcliente.setContentAreaFilled(false);
        crearcliente.setBorderPainted(false);

        editar.setOpaque(false);
        editar.setContentAreaFilled(false);
        editar.setBorderPainted(false);

        eliminarcliente.setOpaque(false);
        eliminarcliente.setContentAreaFilled(false);
        eliminarcliente.setBorderPainted(false);

        subpanel1.setOpaque(false);
        panelprincipal.setOpaque(false);

    }
//   DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        transparecia();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        int ancho = (int) tamanio.getWidth();
        int alto = (int) tamanio.getHeight();
        this.setSize(new Dimension(ancho, alto));
//        this.setResizable(false);
        jLabel1.setPreferredSize(new Dimension(ancho, alto));
        ImageIcon rm = new ImageIcon(getClass().getResource("/img/rm.jpg"));
        Icon fondo = new ImageIcon(rm.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(fondo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        subpanel1 = new javax.swing.JPanel();
        panelprincipal = new javax.swing.JPanel();
        txtbuscar = new rojerusan.RSMetroTextFullPlaceHolder();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos = new rojerusan.RSTableMetro();
        eliminarcliente = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        abrirarchivos = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        crearcliente = new javax.swing.JButton();
        configuraciones1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subpanel1.setMaximumSize(new java.awt.Dimension(1280, 1080));
        subpanel1.setName("subpanel1"); // NOI18N
        subpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setBackground(new java.awt.Color(255, 153, 153));
        panelprincipal.setMaximumSize(new java.awt.Dimension(1280, 1080));
        panelprincipal.setName("panelpricipal"); // NOI18N
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelprincipal.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabladatos.setRowHeight(30);
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabladatos);

        panelprincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1000, 460));

        eliminarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminaruser.png"))); // NOI18N
        panelprincipal.add(eliminarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 90, -1));

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        panelprincipal.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        abrirarchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        abrirarchivos.setBorder(null);
        abrirarchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirarchivosActionPerformed(evt);
            }
        });
        panelprincipal.add(abrirarchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 90, 80));

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        panelprincipal.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        subpanel1.add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 620));

        jPanel1.add(subpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 620));

        menu.setBackground(new java.awt.Color(244, 241, 241));
        menu.setName("menu"); // NOI18N

        crearcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearuser.png"))); // NOI18N
        crearcliente.setText("Crearcliente");
        crearcliente.setBorder(null);

        configuraciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones (2).png"))); // NOI18N
        configuraciones1.setText("Configuraciones");
        configuraciones1.setBorder(null);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(configuraciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(crearcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(688, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configuraciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rm1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
//        Usuario mod = new Usuario();
//        
//        Registro_Usuario resgistrar_usuario = new Registro_Usuario(this, true);
//        UsuarioController ctrl = new UsuarioController(mod, modc, resgistrar_usuario);
//        ctrl.iniciar();
//        resgistrar_usuario.setVisible(true);
    }//GEN-LAST:event_registrarActionPerformed

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
//                int selecionar = tabladatos.rowAtPoint(evt.getPoint());

    }//GEN-LAST:event_tabladatosMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        
    }//GEN-LAST:event_editarActionPerformed

    private void abrirarchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirarchivosActionPerformed

    }//GEN-LAST:event_abrirarchivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton abrirarchivos;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton configuraciones1;
    public javax.swing.JButton crearcliente;
    public javax.swing.JButton editar;
    public javax.swing.JButton eliminarcliente;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JButton registrar;
    private javax.swing.JPanel subpanel1;
    public rojerusan.RSTableMetro tabladatos;
    public rojerusan.RSMetroTextFullPlaceHolder txtbuscar;
    // End of variables declaration//GEN-END:variables
}
