/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Consultas.Consultas_Clase;
import Consultas.Consultas_Cliente_Potencial;
import Consultas.Consultas_Configuraciones;
import Consultas.Consultas_Directorio;
import Consultas.Consultas_Documentos;
import Consultas.Consultas_Llego;
import Consultas.Consultas_Servicio;
import Consultas.Consultas_Servicios_has_Clientes_Potenciales;
import Consultas.Consultas_usuario;
import buscador.Dialogos;
import controlador.ClaseController;
import controlador.Cliente_PotencialController;
import controlador.ConfiguracionesController;
import controlador.DirectorioController;
import controlador.EditarController;
import controlador.LlegoController;
import controlador.ServicioController;
import controlador.UsuarioController;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Clases;
import modelo.Cliente_Potencial;
import modelo.Configuracion;
import modelo.Directorio;
import modelo.Documentos;
import modelo.Llego;
import modelo.Servicio;
import modelo.Servicios_has_Clientes_Potenciales;

/**
 *
 * @author Yonathan Carvajal
 */
public class Principal extends javax.swing.JFrame {

    Servicio mods = new Servicio();
    Consultas_Servicio servicio = new Consultas_Servicio();

    Servicios_has_Clientes_Potenciales shcp = new Servicios_has_Clientes_Potenciales();
    Consultas_Servicios_has_Clientes_Potenciales cshcp = new Consultas_Servicios_has_Clientes_Potenciales();

    Configuracion mconfiguracion = new Configuracion();
    Consultas_Configuraciones cconfiguraciones = new Consultas_Configuraciones();
    Configuraciones vc = new Configuraciones(this, true);

    Cliente_Potencial modelo = new Cliente_Potencial();

    Documentos documento = new Documentos();
    Consultas_Documentos cdocumentos = new Consultas_Documentos();

    Consultas_Cliente_Potencial consulta = new Consultas_Cliente_Potencial();

    Consultas_Clase conc = new Consultas_Clase();
    Clases mc = new Clases();

    Consultas_Llego conl = new Consultas_Llego();
    Llego ml = new Llego();

    Directorio mod1 = new Directorio();
    Consultas_Directorio modc1 = new Consultas_Directorio();

    Formulario formulario = new Formulario(this, true);
    Editarcliente editarcliente = new Editarcliente(this, true);

    public void transparecia() {

        abrirarchivos.setOpaque(false);
        abrirarchivos.setContentAreaFilled(false);
        abrirarchivos.setBorderPainted(false);

        editar.setOpaque(false);
        editar.setContentAreaFilled(false);
        editar.setBorderPainted(false);

        eliminarcliente.setOpaque(false);
        eliminarcliente.setContentAreaFilled(false);
        eliminarcliente.setBorderPainted(false);

        subpanel1.setOpaque(false);
        panelprincipal.setOpaque(false);

    }
//   DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        transparecia();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
        int ancho = (int) tamanio.getWidth();
        int alto = (int) tamanio.getHeight();
        this.setResizable(true);
        jLabel1.setPreferredSize(new Dimension(ancho, alto));
        ImageIcon rm = new ImageIcon(getClass().getResource("/img/rm.jpg"));
        Icon fondo = new ImageIcon(rm.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        subpanel1 = new javax.swing.JPanel();
        panelprincipal = new javax.swing.JPanel();
        txtbuscar = new rojerusan.RSMetroTextFullPlaceHolder();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos = new rojerusan.RSTableMetro();
        eliminarcliente = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        abrirarchivos = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnbuscar = new javax.swing.JMenu();
        configuraciones1 = new javax.swing.JMenu();
        Crearcliente = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        setMaximumSize(new java.awt.Dimension(1280, 1080));

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subpanel1.setMaximumSize(new java.awt.Dimension(1280, 1080));
        subpanel1.setName("subpanel1"); // NOI18N
        subpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setBackground(new java.awt.Color(255, 153, 153));
        panelprincipal.setMaximumSize(new java.awt.Dimension(1280, 1080));
        panelprincipal.setName("panelpricipal"); // NOI18N
        panelprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelprincipal.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabladatos.setRowHeight(30);
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabladatos);

        panelprincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1000, 460));

        eliminarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminaruser.png"))); // NOI18N
        panelprincipal.add(eliminarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 90, -1));

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        panelprincipal.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        abrirarchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open.png"))); // NOI18N
        abrirarchivos.setBorder(null);
        abrirarchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirarchivosActionPerformed(evt);
            }
        });
        panelprincipal.add(abrirarchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 90, 80));

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        panelprincipal.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        subpanel1.add(panelprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        jPanel1.add(subpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1060, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rm1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 72));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnbuscar);

        configuraciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones (2).png"))); // NOI18N
        configuraciones1.setText("Configuraciones");
        configuraciones1.setPreferredSize(new java.awt.Dimension(170, 64));
        configuraciones1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configuraciones1MouseClicked(evt);
            }
        });
        jMenuBar1.add(configuraciones1);

        Crearcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearuser.png"))); // NOI18N
        Crearcliente.setText("Crear Cliente");
        Crearcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearclienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(Crearcliente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
//        Usuario mod = new Usuario();
//        
//        Registro_Usuario resgistrar_usuario = new Registro_Usuario(this, true);
//        UsuarioController ctrl = new UsuarioController(mod, modc, resgistrar_usuario);
//        ctrl.iniciar();
//        resgistrar_usuario.setVisible(true);
    }//GEN-LAST:event_registrarActionPerformed

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
//                int selecionar = tabladatos.rowAtPoint(evt.getPoint());

    }//GEN-LAST:event_tabladatosMouseClicked

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        int selecionar = tabladatos.getSelectedRow();
        if (selecionar != -1) {
            modelo.setIdclientes_potenciales(Integer.parseInt(String.valueOf(tabladatos.getValueAt(selecionar, 0))));
            EditarController editarcli = new EditarController(modelo, mods, shcp, documento,
                    mconfiguracion, servicio, consulta, cshcp, cdocumentos, cconfiguraciones, conc, conl,
                    editarcliente);
            editarcli.iniciar();
            editarcliente.setVisible(true);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void abrirarchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirarchivosActionPerformed

    }//GEN-LAST:event_abrirarchivosActionPerformed

    private void configuraciones1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuraciones1MouseClicked

        ServicioController ctrl = new ServicioController(mods, servicio, vc);
        ctrl.iniciar();
        //otros

        ClaseController cctrl = new ClaseController(conc, mc, vc);
        cctrl.iniciar();

        LlegoController lc = new LlegoController(ml, conl, vc);
        lc.iniciar();
        //directorio

        DirectorioController ctrc = new DirectorioController(modc1, mod1, vc);
        ctrc.iniciar();

        ConfiguracionesController ccontroller = new ConfiguracionesController(mconfiguracion, cconfiguraciones, vc);
        ccontroller.iniciar();
        vc.setVisible(true);
    }//GEN-LAST:event_configuraciones1MouseClicked

    private void CrearclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearclienteMouseClicked

        Cliente_PotencialController controlador = new Cliente_PotencialController(modelo, consulta,
                formulario, servicio, mods, shcp, cshcp, documento, cdocumentos,
                mconfiguracion, cconfiguraciones);
        controlador.iniciar();
        formulario.setVisible(true);


    }//GEN-LAST:event_CrearclienteMouseClicked

    private void btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseClicked
        panelprincipal.setVisible(true);
    }//GEN-LAST:event_btnbuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Crearcliente;
    public javax.swing.JButton abrirarchivos;
    private javax.swing.JMenu btnbuscar;
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu configuraciones1;
    public javax.swing.JButton editar;
    public javax.swing.JButton eliminarcliente;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JButton registrar;
    private javax.swing.JPanel subpanel1;
    public rojerusan.RSTableMetro tabladatos;
    public rojerusan.RSMetroTextFullPlaceHolder txtbuscar;
    // End of variables declaration//GEN-END:variables
}
